"""
157.389. Find the Difference
找不同


Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.


"""


return chr(sum(map(ord, t)) - sum(map(ord, s)))

return chr(reduce(int.__xor__, map(ord, s+t)))
return chr(reduce(operator.xor, map(ord, s + t)))




return list((Counter(t) - Counter(s)).keys())[0]
return [i for i in t if i not in s or s.count(i)!=t.count(i)][0]


return next((c for c, d in zip(sorted(t), sorted(s)) if c != d), max(t))
return next(c for c, d in zip(sorted(t), sorted(s) + [None]) if c != d)
return next(c for c, d in map(None, sorted(t), sorted(s)) if c != d)
return filter(None, map(lambda c, d: c != d and c, sorted(t), sorted(s)))[0]


s, t = sorted(s), sorted(t)
return t[-1] if s == t[:-1] else [x[1] for x in zip(s, t) if x[0] != x[1]][0]


return [c for c in set(s+t) if (s+t).count(c) % 2 == 1][0]





def findTheDifference(self, s, t):
    dic = {}
    for ch in s:
        dic[ch] = dic.get(ch, 0) + 1
    for ch in t:
        if dic.get(ch, 0) == 0:
            return ch
        else:
            dic[ch] -= 1


def findTheDifference(self, s, t):
    diff = 0
    for i in range(len(s)):
        diff -= ord(s[i])
        diff += ord(t[i])
    diff += ord(t[-1])
    return chr(diff)


def findTheDifference(self, s, t):
    code = 0
    for ch in s + t:
        code ^= ord(ch)
    return chr(code)





















































